EXECUTE PKG_COMISIONES_AUDITORIA.PRC_CALCULAR_COMISION_AUDITOR(50, '202311');

-- Ver detalle por auditor y empresa
SELECT * FROM DETALLE_COMISIONES_AUDITORIAS_MES
WHERE run_auditor = '6057969-6';

-- Ver errores registrados
SELECT * FROM ERROR_PROCESO
ORDER BY correlativo DESC;
