/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER Encargo_1 IDENTIFIED BY "Contrasenadificil#01"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER Encargo_1 QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO Encargo_1;
GRANT "RESOURCE" TO Encargo_1;
GRANT CREATE SEQUENCE TO Encargo_1;
ALTER USER Encargo_1 DEFAULT ROLE "RESOURCE";